# Generated by Django 5.2.8 on 2025-12-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user',
        ),
    ]
