# Generated by Django 5.2.8 on 2025-12-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cls',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='fee',
            field=models.FloatField(),
        ),
    ]
